### ISSUE TITLE
Any interest in separation of id-tree and event-tree?

### ISSUE THREAD

**Issue by tv42** [fgrid/itc#6]
I'm still learning this myself, but apparently, sometimes one needs to pre-fork the id-tree to all nodes in a cluster. For an example in Cassandra, see https://issues.apache.org/jira/browse/CASSANDRA-580?focusedCommentId=12787092&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12787092

I have a sort of similar need. I'm trying to space-efficiently store millions of version vectors, all with the same peers, and I _think_ I could use ITC and share the same id-tree across all of the items. I'm still trying to wrap my around all the implications of that.

Do you have any interest in evolving the API here toward a more complex one that would allow id-tree and event-tree separation, or do you want to keep this library as the simplest possible thing? Are you still interested in evolving this library forward, or did you achieve all your personal goals already? I'll happily go experiment in a fork, or make my own package as a whole, but I figured I should ask first.

**Comment by stephanheinze** [comment]
I am out of town at the moment. But I think will have a look into this next week.

**Comment by stephanheinze** [comment]
Wooo ... interesting stuff.

First I'd like to say, that in the ITC paper IDs are NOT IDs of values - they are identifiers of replicas or in other words: identifiers of nodes. And the ID tree represents **one** ID - not the tree of many. And with every fork and every join you change the ID itself.

So in ITC the purpose of the ID tree is the identification of a replica to order the events until the next contact with the cluster (the join). And you should join regulary to keep the ITC small enough.

That's how **I** understand ITC :-)

But if you can reuse the id-tree implementation for another purpose I'll happily separate the code.

I think, the golang-way would be a new package to prevent API pollution of the ITC package.
I'm open for advise.

**Comment by stephanheinze** [comment]
Separated to subpackage 'id'.
Feel free to experiment with the code.
